### ISSUE TITLE
dbcDeploy should only reupload snaphots

### ISSUE THREAD

**Issue by MasseGuillaume** [databricks/sbt-databricks#3]
For example, a project depends on quasiquotes
Deleting older version of quasiquotes_2.10-2.0.1.jar
Uploading quasiquotes_2.10-2.0.1.jar
Attaching quasiquotes_2.10-2.0.1.jar to cluster 'db_20150407

quasiquotes_2.10-2.0.1 was released 2014-06-28 14:18:36 UTC and is unlikely to change.
http://maven-repository.com/artifact/org.scalamacros/quasiquotes_2.10/2.0.1

I think a good heuristic could be to look if the version contains "-SNAPSHOT".

**Comment by brkyvz** [comment]
Resolved with PR #4
