### ISSUE TITLE
dbcDeploy problem : Stack trace suppressed

### ISSUE THREAD

**Issue by adiautodesk** [databricks/sbt-databricks#33]
I was trying to integrate intelliJ IDE with databricks using the link : 

https://docs.cloud.databricks.com/docs/latest/databricks_guide/02%20Product%20Overview/12%20IDE%20Plugin.html

While following the tutorial, I am stuck at step 4, where I need to use dbcDeploy. While executing that command, I am getting the following error: 

> dbcDeploy
[trace] Stack trace suppressed: run 'last *:dbcFetchClusters' for the full output.
[error] (*:dbcFetchClusters) com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
[error]  at [Source: <!DOCTYPE html>
[error] 
[error] <html>
[error] <head>
[error]   <meta charset="utf-8"/>
[error]   <meta http-equiv="Content-Language" content="en"/>
[error]   <title>Databricks - Sign In</title>
[error]   <meta name="viewport" content="width=960">
[error]   <link rel="stylesheet" href="/lib/css/bootstrap.min.css">
[error]   <link rel="stylesheet" href="/css/main.css">
[error]   <link rel="stylesheet" href="/css/login.css">
[error]   <link rel="icon" type="image/png" href="img/favicon.ico" />
[error] 
[error]   <meta http-equiv="content-type" content="text/html; charset=UTF8">
[error] </head>
[error] <body>
[error]   <div id="login-page"></div>
[error]   <script src="/js/login-main.js"></script>
[error] </body>
[error] </html>
[error] ; line: 1, column: 2]
[error] Total time: 2 s, completed Jun 13, 2016 9:24:10 PM

Can Anyone tell me what could be the issue here?

**Comment by adiautodesk** [comment]
> dbcDeploy
[trace] Stack trace suppressed: run 'last *:dbcFetchClusters' for the full output.
[error] (*:dbcFetchClusters) com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
[error]  at [Source: <!DOCTYPE html>
[error] 
[error] <html>
[error] <head>
[error]   <meta charset="utf-8"/>
[error]   <meta http-equiv="Content-Language" content="en"/>
[error]   <title>Databricks - Sign In</title>
[error]   <meta name="viewport" content="width=960">
[error]   <link rel="stylesheet" href="/lib/css/bootstrap.min.css">
[error]   <link rel="stylesheet" href="/css/main.css">
[error]   <link rel="stylesheet" href="/css/login.css">
[error]   <link rel="icon" type="image/png" href="img/favicon.ico" />
[error] 
[error]   <meta http-equiv="content-type" content="text/html; charset=UTF8">
[error] </head>
[error] <body>
[error]   <div id="login-page"></div>
[error]   <script src="/js/login-main.js"></script>
[error] </body>
[error] </html>
[error] ; line: 1, column: 2]
[error] Total time: 2 s, completed Jun 13, 2016 9:24:10 PM

**Comment by brkyvz** [comment]
Could you please verify that your 'dbcApiUrl' ends with /api/1.2?

**Comment by adiautodesk** [comment]
How can i verify that ? I am currently using https://<hidden>.cloud.databricks.com/#notebook/118275/api/1.2

Sorry, If thats a dumb question. I am new to databricks. I was looking at databricks REST api documentation and i got to know about 2 REST api releases i.e. 1.2 and 2.0. I have tried with both the links and I could not login. received the following error:
 {"error_code":"MALFORMED_REQUEST","message":"Request path is malformed"}

Do i need to setup REST api?

**Comment by brkyvz** [comment]
Could you please remove `#notebook/118275/` from your URL and try again?

**Comment by brkyvz** [comment]
simply try `https://<organization>.cloud.databricks.com/api/1.2`

**Comment by adiautodesk** [comment]
sorry that was a typo..I tried without notebook as well. Let me try https://<organization>.cloud.databricks.com/api/1.2 .

**Comment by adiautodesk** [comment]
That site can't be reached.

**Comment by brkyvz** [comment]
could you please share the snippet of your Build file that sets the plugin keys please?

**Comment by adiautodesk** [comment]
My plugins.sbt file is as follows: 

logLevel := Level.Warn
addSbtPlugin("com.databricks" %% "sbt-databricks" % "0.1.5")

build.sbt file is as follows:

name := "sparkDemo"

version := "1.0"

scalaVersion := "2.11.8"

// Your username to login to Databricks
dbcUsername := "myUserNameForDatabricks"// e.g. "admin"

// Your password (Can be set as an environment variable)
dbcPassword := "myPassword"// e.g. "admin" or System.getenv("DBCLOUD_PASSWORD")
// Gotcha: Setting environment variables in IDE's may differ. IDE's usually don't pick up environment variables from .bash_profile or .bashrc

// The URL to the Databricks REST API.
dbcApiUrl := "http://myOrganization.cloud.databricks.com/api/2.0"// "https://organization.cloud.databricks.com/api/1.2"

// Add any clusters that you would like to deploy your work to. e.g. "My Cluster"
dbcClusters += "myClusterName"// Add "ALL_CLUSTERS" if you want to attach your work to all clusters

// An optional parameter to set the location to upload your libraries to in the workspace e.g. "/home/USER/libraries"
// This location must be an existing path.
// NOTE: Specifying this parameter is *strongly* recommended as many jars will be uploaded to your cluster.
// Putting them in one folder will make it easy for your to delete all the libraries at once.
dbcLibraryPath := "/home/USER/libraries"  // Default is "/"

// Whether to restart the clusters everytime a new version is uploaded to Databricks.
dbcRestartOnAttach := true // Default true.

//resolvers := "http://central.maven.org/maven2/com/databricks/spark-csv_2.10/0.1/spark-csv_2.10-0.1.pom”

**Comment by brkyvz** [comment]
Just to be sure that it's not a typo:
Could you please change the `dbcApiUrl` to be `https` and point to `api/1.2` instead of `api/2.0`?

**Comment by adiautodesk** [comment]
Yeah i tried that. No success.
tried the following:
dbcApiUrl := "https://myOrganizationName.cloud.databricks.com/api/1.2"

**Comment by anabranch** [comment]
Have you seen this template?
https://github.com/anabranch/Apache-Spark-Scala-Project-Template/blob/master/build.sbt

This might help you make sure there's no user error. All you need to do is correctly set 
- Environment variables for username and pass
- Change the URL to your organization name.

I wrote that to make it easy to create your own Spark Scala projects.

**Comment by brkyvz** [comment]
And you normally use Databricks through "https://myOrganizationName.cloud.databricks.com" correct?
Could you please reach out to `support@databricks.com`? Do you happen to have SSO enabled in your organization?

**Comment by adiautodesk** [comment]
I dont actually use the "myOrganizationName" in the url. I do have a separate url. I have used both the combinations though. Let me check if SSO is enabled or not.

**Comment by anabranch** [comment]
Please try the template that I included as it's a simple example to make sure that it's not something on your end. if that doesn't work please follow up with support@databricks and we can help you that way :)

**Comment by brkyvz** [comment]
You will have to use the URL that you login to Databricks with + `/api/1.2`.

**Comment by adiautodesk** [comment]
Burak, I tried that.
Bill, you mean the tempalate in https://docs.cloud.databricks.com/docs/latest/databricks_guide/02%20Product%20Overview/12%20IDE%20Plugin.html 
?? I have verified and using the same template.

**Comment by anabranch** [comment]
@adiautodesk The one here:
https://github.com/anabranch/Apache-Spark-Scala-Project-Template

I have used this and can confirm that it works exactly as is. You just need to swap out:

Environment variables for username and pass
Change the URL to have your organization name instead of the filler in there now.

**Comment by adiautodesk** [comment]
Bill, Let me try that. Thanks!!

**Comment by adiautodesk** [comment]
@brkyvz : we don't have SSO with databricks. can that be an issue?

**Comment by anabranch** [comment]
@adiautodesk No, not having SSO has no effect on the REST API, so not having SSO is *not* the issue.

**Comment by anabranch** [comment]
We haven't heard anything from you so I'm assuming this was able to help you fix the issue!
