### ISSUE TITLE
dbcCreateCluster not a valid key

### ISSUE THREAD

**Issue by briantd** [databricks/sbt-databricks#36]
When I try and use dbcCreateCluster, I get an error.  Likewise, the required setting dbcNumWorkerContainers is not recognized.  Other commands like dbcListClusters, dbcDeploy, or dbcRestartClusters work fine.

I'm using the latest version of Databricks, and have the required config installed in project/plugins.sbt (as evidenced by being able to run dbcListCluters, and dbcDeploy).
--> addSbtPlugin("com.databricks" %% "sbt-databricks" % "0.1.5")

**Comment by brkyvz** [comment]
Hi @briantd,
Can you please provide a stack trace of the error?

**Comment by brkyvz** [comment]
In addition, do you use a `.sbt` file or `.scala` file for your Build?

**Comment by anabranch** [comment]
@briantd closing this out for now, please re-open if this still isn't resolved.

**Comment by the-jackalope** [comment]
Hi @brkyvz 

I'm using sbt-databricks v0.1.5 and I have the same problem. IntelliJ wasn't picking up on a `dbcCreateCluster` task so I ran `sbt dbcCreateCluster` and I got the generic error:
```
[error] Not a valid command: dbcCreateCluster
[error] Not a valid key: dbcCreateCluster (similar: dbcRestartClusters, dbcFetchClusters, dbcClusters)
[error] dbcCreateCluster
```
Let me know if I can provide more info!
