### ISSUE TITLE
multiproject does not include dependsOn

### ISSUE THREAD

**Issue by MasseGuillaume** [databricks/sbt-databricks#5]
This is wrong: https://github.com/databricks/sbt-databricks/blob/master/src/main/scala/sbtdatabricks/DatabricksPlugin.scala#L68

given
project a
project b with libs depends on a
when
b/dbcDeploy
actual
b and libs are available
expected
a, b and libs are available

**Comment by brkyvz** [comment]
Resolved with PR #4
